package aduana.modelo;
// Generated 11-30-2016 03:24:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Arancel generated by hbm2java
 */
public class Arancel  implements java.io.Serializable {


     private int idArancel;
     private Tipoarancel tipoarancel;
     private double precioArancel;
     private Set<Producto> productos = new HashSet<Producto>(0);

    public Arancel() {
    }

	
    public Arancel(int idArancel, double precioArancel) {
        this.idArancel = idArancel;
        this.precioArancel = precioArancel;
    }
    public Arancel(int idArancel, Tipoarancel tipoarancel, double precioArancel, Set<Producto> productos) {
       this.idArancel = idArancel;
       this.tipoarancel = tipoarancel;
       this.precioArancel = precioArancel;
       this.productos = productos;
    }
   
    public int getIdArancel() {
        return this.idArancel;
    }
    
    public void setIdArancel(int idArancel) {
        this.idArancel = idArancel;
    }
    public Tipoarancel getTipoarancel() {
        return this.tipoarancel;
    }
    
    public void setTipoarancel(Tipoarancel tipoarancel) {
        this.tipoarancel = tipoarancel;
    }
    public double getPrecioArancel() {
        return this.precioArancel;
    }
    
    public void setPrecioArancel(double precioArancel) {
        this.precioArancel = precioArancel;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }




}


