package aduana.modelo;
// Generated 11-20-2016 10:33:46 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Arancel generated by hbm2java
 */
public class Arancel  implements java.io.Serializable {


     private int idArancel;
     private Tipoarancel tipoarancel;
     private String precioArancel;
     private Set productos = new HashSet(0);

    public Arancel() {
    }

	
    public Arancel(int idArancel, String precioArancel) {
        this.idArancel = idArancel;
        this.precioArancel = precioArancel;
    }
    public Arancel(int idArancel, Tipoarancel tipoarancel, String precioArancel, Set productos) {
       this.idArancel = idArancel;
       this.tipoarancel = tipoarancel;
       this.precioArancel = precioArancel;
       this.productos = productos;
    }
   
    public int getIdArancel() {
        return this.idArancel;
    }
    
    public void setIdArancel(int idArancel) {
        this.idArancel = idArancel;
    }
    public Tipoarancel getTipoarancel() {
        return this.tipoarancel;
    }
    
    public void setTipoarancel(Tipoarancel tipoarancel) {
        this.tipoarancel = tipoarancel;
    }
    public String getPrecioArancel() {
        return this.precioArancel;
    }
    
    public void setPrecioArancel(String precioArancel) {
        this.precioArancel = precioArancel;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


