package aduana.modelo;
// Generated 11-30-2016 03:24:13 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Formularioexportacion generated by hbm2java
 */
public class Formularioexportacion  implements java.io.Serializable {


     private int idFe;
     private Pago pago;
     private Pais pais;
     private Transporte transporte;
     private Usuario usuario;
     private String codigoFe;
     private String origenFe;
     private String instanciasFe;
     private String observacionesFe;
     private Date fechaFe;

    public Formularioexportacion() {
    }

    public Formularioexportacion(int idFe, Pago pago, Pais pais, Transporte transporte, Usuario usuario, String codigoFe, String origenFe, String instanciasFe, String observacionesFe, Date fechaFe) {
       this.idFe = idFe;
       this.pago = pago;
       this.pais = pais;
       this.transporte = transporte;
       this.usuario = usuario;
       this.codigoFe = codigoFe;
       this.origenFe = origenFe;
       this.instanciasFe = instanciasFe;
       this.observacionesFe = observacionesFe;
       this.fechaFe = fechaFe;
    }
   
    public int getIdFe() {
        return this.idFe;
    }
    
    public void setIdFe(int idFe) {
        this.idFe = idFe;
    }
    public Pago getPago() {
        return this.pago;
    }
    
    public void setPago(Pago pago) {
        this.pago = pago;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public Transporte getTransporte() {
        return this.transporte;
    }
    
    public void setTransporte(Transporte transporte) {
        this.transporte = transporte;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getCodigoFe() {
        return this.codigoFe;
    }
    
    public void setCodigoFe(String codigoFe) {
        this.codigoFe = codigoFe;
    }
    public String getOrigenFe() {
        return this.origenFe;
    }
    
    public void setOrigenFe(String origenFe) {
        this.origenFe = origenFe;
    }
    public String getInstanciasFe() {
        return this.instanciasFe;
    }
    
    public void setInstanciasFe(String instanciasFe) {
        this.instanciasFe = instanciasFe;
    }
    public String getObservacionesFe() {
        return this.observacionesFe;
    }
    
    public void setObservacionesFe(String observacionesFe) {
        this.observacionesFe = observacionesFe;
    }
    public Date getFechaFe() {
        return this.fechaFe;
    }
    
    public void setFechaFe(Date fechaFe) {
        this.fechaFe = fechaFe;
    }




}


