package aduana.modelo;
<<<<<<< HEAD
// Generated 11-30-2016 03:24:13 PM by Hibernate Tools 4.3.1


=======
// Generated 11-20-2016 10:33:46 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
>>>>>>> ded8ed45bf60eccdd9124f32bde57f757b9c0fe3

/**
 * Formularioarancelario generated by hbm2java
 */
public class Formularioarancelario  implements java.io.Serializable {


<<<<<<< HEAD
     private int idFa;
     private Producto producto;
     private Usuario usuario;
     private String codarancelarioFa;
=======
     private int idFormarancelario;
     private Usuario usuario;
     private String codarancelarioFormarancelario;
     private Set productos = new HashSet(0);
>>>>>>> ded8ed45bf60eccdd9124f32bde57f757b9c0fe3

    public Formularioarancelario() {
    }

<<<<<<< HEAD
    public Formularioarancelario(int idFa, Producto producto, Usuario usuario, String codarancelarioFa) {
       this.idFa = idFa;
       this.producto = producto;
       this.usuario = usuario;
       this.codarancelarioFa = codarancelarioFa;
    }
   
    public int getIdFa() {
        return this.idFa;
    }
    
    public void setIdFa(int idFa) {
        this.idFa = idFa;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
=======
	
    public Formularioarancelario(int idFormarancelario, String codarancelarioFormarancelario) {
        this.idFormarancelario = idFormarancelario;
        this.codarancelarioFormarancelario = codarancelarioFormarancelario;
    }
    public Formularioarancelario(int idFormarancelario, Usuario usuario, String codarancelarioFormarancelario, Set productos) {
       this.idFormarancelario = idFormarancelario;
       this.usuario = usuario;
       this.codarancelarioFormarancelario = codarancelarioFormarancelario;
       this.productos = productos;
    }
   
    public int getIdFormarancelario() {
        return this.idFormarancelario;
    }
    
    public void setIdFormarancelario(int idFormarancelario) {
        this.idFormarancelario = idFormarancelario;
>>>>>>> ded8ed45bf60eccdd9124f32bde57f757b9c0fe3
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
<<<<<<< HEAD
    public String getCodarancelarioFa() {
        return this.codarancelarioFa;
    }
    
    public void setCodarancelarioFa(String codarancelarioFa) {
        this.codarancelarioFa = codarancelarioFa;
=======
    public String getCodarancelarioFormarancelario() {
        return this.codarancelarioFormarancelario;
    }
    
    public void setCodarancelarioFormarancelario(String codarancelarioFormarancelario) {
        this.codarancelarioFormarancelario = codarancelarioFormarancelario;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
>>>>>>> ded8ed45bf60eccdd9124f32bde57f757b9c0fe3
    }




}


