package aduana.modelo;
<<<<<<< HEAD
// Generated 11-30-2016 03:24:13 PM by Hibernate Tools 4.3.1


import java.util.Date;
=======
// Generated 11-20-2016 10:33:46 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
>>>>>>> ded8ed45bf60eccdd9124f32bde57f757b9c0fe3

/**
 * Formularioexportacion generated by hbm2java
 */
public class Formularioexportacion  implements java.io.Serializable {


<<<<<<< HEAD
     private int idFe;
     private Pago pago;
     private Pais pais;
     private Transporte transporte;
     private Usuario usuario;
     private String codigoFe;
     private String origenFe;
     private String instanciasFe;
     private String observacionesFe;
     private Date fechaFe;
=======
     private int idFormexpor;
     private Transporte transporte;
     private Usuario usuario;
     private String codigoFormexpor;
     private String origenFormexpor;
     private String instanciasFormexpor;
     private String observacionesFormexpor;
     private Date fechaFormexpor;
     private Set paises = new HashSet(0);
     private Set pagos = new HashSet(0);
>>>>>>> ded8ed45bf60eccdd9124f32bde57f757b9c0fe3

    public Formularioexportacion() {
    }

<<<<<<< HEAD
    public Formularioexportacion(int idFe, Pago pago, Pais pais, Transporte transporte, Usuario usuario, String codigoFe, String origenFe, String instanciasFe, String observacionesFe, Date fechaFe) {
       this.idFe = idFe;
       this.pago = pago;
       this.pais = pais;
       this.transporte = transporte;
       this.usuario = usuario;
       this.codigoFe = codigoFe;
       this.origenFe = origenFe;
       this.instanciasFe = instanciasFe;
       this.observacionesFe = observacionesFe;
       this.fechaFe = fechaFe;
    }
   
    public int getIdFe() {
        return this.idFe;
    }
    
    public void setIdFe(int idFe) {
        this.idFe = idFe;
    }
    public Pago getPago() {
        return this.pago;
    }
    
    public void setPago(Pago pago) {
        this.pago = pago;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
=======
	
    public Formularioexportacion(int idFormexpor, String codigoFormexpor, String origenFormexpor, String instanciasFormexpor, String observacionesFormexpor, Date fechaFormexpor) {
        this.idFormexpor = idFormexpor;
        this.codigoFormexpor = codigoFormexpor;
        this.origenFormexpor = origenFormexpor;
        this.instanciasFormexpor = instanciasFormexpor;
        this.observacionesFormexpor = observacionesFormexpor;
        this.fechaFormexpor = fechaFormexpor;
    }
    public Formularioexportacion(int idFormexpor, Transporte transporte, Usuario usuario, String codigoFormexpor, String origenFormexpor, String instanciasFormexpor, String observacionesFormexpor, Date fechaFormexpor, Set paises, Set pagos) {
       this.idFormexpor = idFormexpor;
       this.transporte = transporte;
       this.usuario = usuario;
       this.codigoFormexpor = codigoFormexpor;
       this.origenFormexpor = origenFormexpor;
       this.instanciasFormexpor = instanciasFormexpor;
       this.observacionesFormexpor = observacionesFormexpor;
       this.fechaFormexpor = fechaFormexpor;
       this.paises = paises;
       this.pagos = pagos;
    }
   
    public int getIdFormexpor() {
        return this.idFormexpor;
    }
    
    public void setIdFormexpor(int idFormexpor) {
        this.idFormexpor = idFormexpor;
>>>>>>> ded8ed45bf60eccdd9124f32bde57f757b9c0fe3
    }
    public Transporte getTransporte() {
        return this.transporte;
    }
    
    public void setTransporte(Transporte transporte) {
        this.transporte = transporte;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
<<<<<<< HEAD
    public String getCodigoFe() {
        return this.codigoFe;
    }
    
    public void setCodigoFe(String codigoFe) {
        this.codigoFe = codigoFe;
    }
    public String getOrigenFe() {
        return this.origenFe;
    }
    
    public void setOrigenFe(String origenFe) {
        this.origenFe = origenFe;
    }
    public String getInstanciasFe() {
        return this.instanciasFe;
    }
    
    public void setInstanciasFe(String instanciasFe) {
        this.instanciasFe = instanciasFe;
    }
    public String getObservacionesFe() {
        return this.observacionesFe;
    }
    
    public void setObservacionesFe(String observacionesFe) {
        this.observacionesFe = observacionesFe;
    }
    public Date getFechaFe() {
        return this.fechaFe;
    }
    
    public void setFechaFe(Date fechaFe) {
        this.fechaFe = fechaFe;
=======
    public String getCodigoFormexpor() {
        return this.codigoFormexpor;
    }
    
    public void setCodigoFormexpor(String codigoFormexpor) {
        this.codigoFormexpor = codigoFormexpor;
    }
    public String getOrigenFormexpor() {
        return this.origenFormexpor;
    }
    
    public void setOrigenFormexpor(String origenFormexpor) {
        this.origenFormexpor = origenFormexpor;
    }
    public String getInstanciasFormexpor() {
        return this.instanciasFormexpor;
    }
    
    public void setInstanciasFormexpor(String instanciasFormexpor) {
        this.instanciasFormexpor = instanciasFormexpor;
    }
    public String getObservacionesFormexpor() {
        return this.observacionesFormexpor;
    }
    
    public void setObservacionesFormexpor(String observacionesFormexpor) {
        this.observacionesFormexpor = observacionesFormexpor;
    }
    public Date getFechaFormexpor() {
        return this.fechaFormexpor;
    }
    
    public void setFechaFormexpor(Date fechaFormexpor) {
        this.fechaFormexpor = fechaFormexpor;
    }
    public Set getPaises() {
        return this.paises;
    }
    
    public void setPaises(Set paises) {
        this.paises = paises;
    }
    public Set getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set pagos) {
        this.pagos = pagos;
>>>>>>> ded8ed45bf60eccdd9124f32bde57f757b9c0fe3
    }




}


