package aduana.modelo;
// Generated 11-30-2016 03:24:13 PM by Hibernate Tools 4.3.1



/**
 * Formularioarancelario generated by hbm2java
 */
public class Formularioarancelario  implements java.io.Serializable {


     private int idFa;
     private Producto producto;
     private Usuario usuario;
     private String codarancelarioFa;

    public Formularioarancelario() {
    }

    public Formularioarancelario(int idFa, Producto producto, Usuario usuario, String codarancelarioFa) {
       this.idFa = idFa;
       this.producto = producto;
       this.usuario = usuario;
       this.codarancelarioFa = codarancelarioFa;
    }
   
    public int getIdFa() {
        return this.idFa;
    }
    
    public void setIdFa(int idFa) {
        this.idFa = idFa;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getCodarancelarioFa() {
        return this.codarancelarioFa;
    }
    
    public void setCodarancelarioFa(String codarancelarioFa) {
        this.codarancelarioFa = codarancelarioFa;
    }




}


