package aduana.modelo;
// Generated 11-20-2016 10:33:46 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Formularioexportacion generated by hbm2java
 */
public class Formularioexportacion  implements java.io.Serializable {


     private int idFormexpor;
     private Transporte transporte;
     private Usuario usuario;
     private String codigoFormexpor;
     private String origenFormexpor;
     private String instanciasFormexpor;
     private String observacionesFormexpor;
     private Date fechaFormexpor;
     private Set paises = new HashSet(0);
     private Set pagos = new HashSet(0);

    public Formularioexportacion() {
    }

	
    public Formularioexportacion(int idFormexpor, String codigoFormexpor, String origenFormexpor, String instanciasFormexpor, String observacionesFormexpor, Date fechaFormexpor) {
        this.idFormexpor = idFormexpor;
        this.codigoFormexpor = codigoFormexpor;
        this.origenFormexpor = origenFormexpor;
        this.instanciasFormexpor = instanciasFormexpor;
        this.observacionesFormexpor = observacionesFormexpor;
        this.fechaFormexpor = fechaFormexpor;
    }
    public Formularioexportacion(int idFormexpor, Transporte transporte, Usuario usuario, String codigoFormexpor, String origenFormexpor, String instanciasFormexpor, String observacionesFormexpor, Date fechaFormexpor, Set paises, Set pagos) {
       this.idFormexpor = idFormexpor;
       this.transporte = transporte;
       this.usuario = usuario;
       this.codigoFormexpor = codigoFormexpor;
       this.origenFormexpor = origenFormexpor;
       this.instanciasFormexpor = instanciasFormexpor;
       this.observacionesFormexpor = observacionesFormexpor;
       this.fechaFormexpor = fechaFormexpor;
       this.paises = paises;
       this.pagos = pagos;
    }
   
    public int getIdFormexpor() {
        return this.idFormexpor;
    }
    
    public void setIdFormexpor(int idFormexpor) {
        this.idFormexpor = idFormexpor;
    }
    public Transporte getTransporte() {
        return this.transporte;
    }
    
    public void setTransporte(Transporte transporte) {
        this.transporte = transporte;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getCodigoFormexpor() {
        return this.codigoFormexpor;
    }
    
    public void setCodigoFormexpor(String codigoFormexpor) {
        this.codigoFormexpor = codigoFormexpor;
    }
    public String getOrigenFormexpor() {
        return this.origenFormexpor;
    }
    
    public void setOrigenFormexpor(String origenFormexpor) {
        this.origenFormexpor = origenFormexpor;
    }
    public String getInstanciasFormexpor() {
        return this.instanciasFormexpor;
    }
    
    public void setInstanciasFormexpor(String instanciasFormexpor) {
        this.instanciasFormexpor = instanciasFormexpor;
    }
    public String getObservacionesFormexpor() {
        return this.observacionesFormexpor;
    }
    
    public void setObservacionesFormexpor(String observacionesFormexpor) {
        this.observacionesFormexpor = observacionesFormexpor;
    }
    public Date getFechaFormexpor() {
        return this.fechaFormexpor;
    }
    
    public void setFechaFormexpor(Date fechaFormexpor) {
        this.fechaFormexpor = fechaFormexpor;
    }
    public Set getPaises() {
        return this.paises;
    }
    
    public void setPaises(Set paises) {
        this.paises = paises;
    }
    public Set getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set pagos) {
        this.pagos = pagos;
    }




}


