package aduana.modelo;
// Generated 11-20-2016 10:33:46 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Formularioarancelario generated by hbm2java
 */
public class Formularioarancelario  implements java.io.Serializable {


     private int idFormarancelario;
     private Usuario usuario;
     private String codarancelarioFormarancelario;
     private Set productos = new HashSet(0);

    public Formularioarancelario() {
    }

	
    public Formularioarancelario(int idFormarancelario, String codarancelarioFormarancelario) {
        this.idFormarancelario = idFormarancelario;
        this.codarancelarioFormarancelario = codarancelarioFormarancelario;
    }
    public Formularioarancelario(int idFormarancelario, Usuario usuario, String codarancelarioFormarancelario, Set productos) {
       this.idFormarancelario = idFormarancelario;
       this.usuario = usuario;
       this.codarancelarioFormarancelario = codarancelarioFormarancelario;
       this.productos = productos;
    }
   
    public int getIdFormarancelario() {
        return this.idFormarancelario;
    }
    
    public void setIdFormarancelario(int idFormarancelario) {
        this.idFormarancelario = idFormarancelario;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getCodarancelarioFormarancelario() {
        return this.codarancelarioFormarancelario;
    }
    
    public void setCodarancelarioFormarancelario(String codarancelarioFormarancelario) {
        this.codarancelarioFormarancelario = codarancelarioFormarancelario;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


