package aduana.modelo;
// Generated 11-20-2016 10:33:46 AM by Hibernate Tools 4.3.1



/**
 * Otrosformularios generated by hbm2java
 */
public class Otrosformularios  implements java.io.Serializable {


     private int idOtrosform;
     private Usuario usuario;

    public Otrosformularios() {
    }

	
    public Otrosformularios(int idOtrosform) {
        this.idOtrosform = idOtrosform;
    }
    public Otrosformularios(int idOtrosform, Usuario usuario) {
       this.idOtrosform = idOtrosform;
       this.usuario = usuario;
    }
   
    public int getIdOtrosform() {
        return this.idOtrosform;
    }
    
    public void setIdOtrosform(int idOtrosform) {
        this.idOtrosform = idOtrosform;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


