package aduana.modelo;
// Generated 11-20-2016 10:33:46 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pago generated by hbm2java
 */
public class Pago  implements java.io.Serializable {


     private int idPago;
     private Catalogopagos catalogopagos;
     private Tipopago tipopago;
     private String codigoPago;
     private String precioPago;
     private Set formularioexportacions = new HashSet(0);
     private Set paises = new HashSet(0);

    public Pago() {
    }

	
    public Pago(int idPago, String codigoPago, String precioPago) {
        this.idPago = idPago;
        this.codigoPago = codigoPago;
        this.precioPago = precioPago;
    }
    public Pago(int idPago, Catalogopagos catalogopagos, Tipopago tipopago, String codigoPago, String precioPago, Set formularioexportacions, Set paises) {
       this.idPago = idPago;
       this.catalogopagos = catalogopagos;
       this.tipopago = tipopago;
       this.codigoPago = codigoPago;
       this.precioPago = precioPago;
       this.formularioexportacions = formularioexportacions;
       this.paises = paises;
    }
   
    public int getIdPago() {
        return this.idPago;
    }
    
    public void setIdPago(int idPago) {
        this.idPago = idPago;
    }
    public Catalogopagos getCatalogopagos() {
        return this.catalogopagos;
    }
    
    public void setCatalogopagos(Catalogopagos catalogopagos) {
        this.catalogopagos = catalogopagos;
    }
    public Tipopago getTipopago() {
        return this.tipopago;
    }
    
    public void setTipopago(Tipopago tipopago) {
        this.tipopago = tipopago;
    }
    public String getCodigoPago() {
        return this.codigoPago;
    }
    
    public void setCodigoPago(String codigoPago) {
        this.codigoPago = codigoPago;
    }
    public String getPrecioPago() {
        return this.precioPago;
    }
    
    public void setPrecioPago(String precioPago) {
        this.precioPago = precioPago;
    }
    public Set getFormularioexportacions() {
        return this.formularioexportacions;
    }
    
    public void setFormularioexportacions(Set formularioexportacions) {
        this.formularioexportacions = formularioexportacions;
    }
    public Set getPaises() {
        return this.paises;
    }
    
    public void setPaises(Set paises) {
        this.paises = paises;
    }




}


