package aduana.modelo;
<<<<<<< HEAD
// Generated 11-30-2016 03:24:13 PM by Hibernate Tools 4.3.1
=======
// Generated 11-20-2016 10:33:46 AM by Hibernate Tools 4.3.1
>>>>>>> ded8ed45bf60eccdd9124f32bde57f757b9c0fe3


import java.util.HashSet;
import java.util.Set;

/**
 * Pago generated by hbm2java
 */
public class Pago  implements java.io.Serializable {


     private int idPago;
     private Catalogopagos catalogopagos;
<<<<<<< HEAD
     private Pais pais;
     private Tipopago tipopago;
     private String codigoPago;
     private String precioPago;
     private Set<Formularioexportacion> formularioexportacions = new HashSet<Formularioexportacion>(0);
=======
     private Tipopago tipopago;
     private String codigoPago;
     private String precioPago;
     private Set formularioexportacions = new HashSet(0);
     private Set paises = new HashSet(0);
>>>>>>> ded8ed45bf60eccdd9124f32bde57f757b9c0fe3

    public Pago() {
    }

	
<<<<<<< HEAD
    public Pago(int idPago, Catalogopagos catalogopagos, Pais pais, Tipopago tipopago, String codigoPago, String precioPago) {
        this.idPago = idPago;
        this.catalogopagos = catalogopagos;
        this.pais = pais;
        this.tipopago = tipopago;
        this.codigoPago = codigoPago;
        this.precioPago = precioPago;
    }
    public Pago(int idPago, Catalogopagos catalogopagos, Pais pais, Tipopago tipopago, String codigoPago, String precioPago, Set<Formularioexportacion> formularioexportacions) {
       this.idPago = idPago;
       this.catalogopagos = catalogopagos;
       this.pais = pais;
=======
    public Pago(int idPago, String codigoPago, String precioPago) {
        this.idPago = idPago;
        this.codigoPago = codigoPago;
        this.precioPago = precioPago;
    }
    public Pago(int idPago, Catalogopagos catalogopagos, Tipopago tipopago, String codigoPago, String precioPago, Set formularioexportacions, Set paises) {
       this.idPago = idPago;
       this.catalogopagos = catalogopagos;
>>>>>>> ded8ed45bf60eccdd9124f32bde57f757b9c0fe3
       this.tipopago = tipopago;
       this.codigoPago = codigoPago;
       this.precioPago = precioPago;
       this.formularioexportacions = formularioexportacions;
<<<<<<< HEAD
=======
       this.paises = paises;
>>>>>>> ded8ed45bf60eccdd9124f32bde57f757b9c0fe3
    }
   
    public int getIdPago() {
        return this.idPago;
    }
    
    public void setIdPago(int idPago) {
        this.idPago = idPago;
    }
    public Catalogopagos getCatalogopagos() {
        return this.catalogopagos;
    }
    
    public void setCatalogopagos(Catalogopagos catalogopagos) {
        this.catalogopagos = catalogopagos;
    }
<<<<<<< HEAD
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
=======
>>>>>>> ded8ed45bf60eccdd9124f32bde57f757b9c0fe3
    public Tipopago getTipopago() {
        return this.tipopago;
    }
    
    public void setTipopago(Tipopago tipopago) {
        this.tipopago = tipopago;
    }
    public String getCodigoPago() {
        return this.codigoPago;
    }
    
    public void setCodigoPago(String codigoPago) {
        this.codigoPago = codigoPago;
    }
    public String getPrecioPago() {
        return this.precioPago;
    }
    
    public void setPrecioPago(String precioPago) {
        this.precioPago = precioPago;
    }
<<<<<<< HEAD
    public Set<Formularioexportacion> getFormularioexportacions() {
        return this.formularioexportacions;
    }
    
    public void setFormularioexportacions(Set<Formularioexportacion> formularioexportacions) {
        this.formularioexportacions = formularioexportacions;
    }
=======
    public Set getFormularioexportacions() {
        return this.formularioexportacions;
    }
    
    public void setFormularioexportacions(Set formularioexportacions) {
        this.formularioexportacions = formularioexportacions;
    }
    public Set getPaises() {
        return this.paises;
    }
    
    public void setPaises(Set paises) {
        this.paises = paises;
    }
>>>>>>> ded8ed45bf60eccdd9124f32bde57f757b9c0fe3




}


