package aduana.modelo;
// Generated 11-30-2016 03:24:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais  implements java.io.Serializable {


     private int idPais;
     private int codigoAreaPais;
     private String codigoPais;
     private String nombrePais;
     private Set<Producto> productosForIdPais = new HashSet<Producto>(0);
     private Set<Aduana> aduanas = new HashSet<Aduana>(0);
     private Set<Pago> pagos = new HashSet<Pago>(0);
     private Set<Producto> productosForPaiIdPais = new HashSet<Producto>(0);
     private Set<Formularioexportacion> formularioexportacions = new HashSet<Formularioexportacion>(0);
     private Set<Departamento> departamentos = new HashSet<Departamento>(0);

    public Pais() {
    }

	
    public Pais(int idPais, int codigoAreaPais, String codigoPais, String nombrePais) {
        this.idPais = idPais;
        this.codigoAreaPais = codigoAreaPais;
        this.codigoPais = codigoPais;
        this.nombrePais = nombrePais;
    }
    public Pais(int idPais, int codigoAreaPais, String codigoPais, String nombrePais, Set<Producto> productosForIdPais, Set<Aduana> aduanas, Set<Pago> pagos, Set<Producto> productosForPaiIdPais, Set<Formularioexportacion> formularioexportacions, Set<Departamento> departamentos) {
       this.idPais = idPais;
       this.codigoAreaPais = codigoAreaPais;
       this.codigoPais = codigoPais;
       this.nombrePais = nombrePais;
       this.productosForIdPais = productosForIdPais;
       this.aduanas = aduanas;
       this.pagos = pagos;
       this.productosForPaiIdPais = productosForPaiIdPais;
       this.formularioexportacions = formularioexportacions;
       this.departamentos = departamentos;
    }
   
    public int getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(int idPais) {
        this.idPais = idPais;
    }
    public int getCodigoAreaPais() {
        return this.codigoAreaPais;
    }
    
    public void setCodigoAreaPais(int codigoAreaPais) {
        this.codigoAreaPais = codigoAreaPais;
    }
    public String getCodigoPais() {
        return this.codigoPais;
    }
    
    public void setCodigoPais(String codigoPais) {
        this.codigoPais = codigoPais;
    }
    public String getNombrePais() {
        return this.nombrePais;
    }
    
    public void setNombrePais(String nombrePais) {
        this.nombrePais = nombrePais;
    }
    public Set<Producto> getProductosForIdPais() {
        return this.productosForIdPais;
    }
    
    public void setProductosForIdPais(Set<Producto> productosForIdPais) {
        this.productosForIdPais = productosForIdPais;
    }
    public Set<Aduana> getAduanas() {
        return this.aduanas;
    }
    
    public void setAduanas(Set<Aduana> aduanas) {
        this.aduanas = aduanas;
    }
    public Set<Pago> getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set<Pago> pagos) {
        this.pagos = pagos;
    }
    public Set<Producto> getProductosForPaiIdPais() {
        return this.productosForPaiIdPais;
    }
    
    public void setProductosForPaiIdPais(Set<Producto> productosForPaiIdPais) {
        this.productosForPaiIdPais = productosForPaiIdPais;
    }
    public Set<Formularioexportacion> getFormularioexportacions() {
        return this.formularioexportacions;
    }
    
    public void setFormularioexportacions(Set<Formularioexportacion> formularioexportacions) {
        this.formularioexportacions = formularioexportacions;
    }
    public Set<Departamento> getDepartamentos() {
        return this.departamentos;
    }
    
    public void setDepartamentos(Set<Departamento> departamentos) {
        this.departamentos = departamentos;
    }




}


