package aduana.modelo;
// Generated 11-20-2016 10:33:46 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais  implements java.io.Serializable {


     private int idPais;
     private Pago pago;
     private int codigoAreaPais;
     private String codigoPais;
     private String nombrePais;
     private Set formularioexportacions = new HashSet(0);
     private Set productosForPaiIdPais = new HashSet(0);
     private Set productosForIdPais = new HashSet(0);
     private Set departamentos = new HashSet(0);
     private Set aduanas = new HashSet(0);

    public Pais() {
    }

	
    public Pais(int idPais, int codigoAreaPais, String codigoPais, String nombrePais) {
        this.idPais = idPais;
        this.codigoAreaPais = codigoAreaPais;
        this.codigoPais = codigoPais;
        this.nombrePais = nombrePais;
    }
    public Pais(int idPais, Pago pago, int codigoAreaPais, String codigoPais, String nombrePais, Set formularioexportacions, Set productosForPaiIdPais, Set productosForIdPais, Set departamentos, Set aduanas) {
       this.idPais = idPais;
       this.pago = pago;
       this.codigoAreaPais = codigoAreaPais;
       this.codigoPais = codigoPais;
       this.nombrePais = nombrePais;
       this.formularioexportacions = formularioexportacions;
       this.productosForPaiIdPais = productosForPaiIdPais;
       this.productosForIdPais = productosForIdPais;
       this.departamentos = departamentos;
       this.aduanas = aduanas;
    }
   
    public int getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(int idPais) {
        this.idPais = idPais;
    }
    public Pago getPago() {
        return this.pago;
    }
    
    public void setPago(Pago pago) {
        this.pago = pago;
    }
    public int getCodigoAreaPais() {
        return this.codigoAreaPais;
    }
    
    public void setCodigoAreaPais(int codigoAreaPais) {
        this.codigoAreaPais = codigoAreaPais;
    }
    public String getCodigoPais() {
        return this.codigoPais;
    }
    
    public void setCodigoPais(String codigoPais) {
        this.codigoPais = codigoPais;
    }
    public String getNombrePais() {
        return this.nombrePais;
    }
    
    public void setNombrePais(String nombrePais) {
        this.nombrePais = nombrePais;
    }
    public Set getFormularioexportacions() {
        return this.formularioexportacions;
    }
    
    public void setFormularioexportacions(Set formularioexportacions) {
        this.formularioexportacions = formularioexportacions;
    }
    public Set getProductosForPaiIdPais() {
        return this.productosForPaiIdPais;
    }
    
    public void setProductosForPaiIdPais(Set productosForPaiIdPais) {
        this.productosForPaiIdPais = productosForPaiIdPais;
    }
    public Set getProductosForIdPais() {
        return this.productosForIdPais;
    }
    
    public void setProductosForIdPais(Set productosForIdPais) {
        this.productosForIdPais = productosForIdPais;
    }
    public Set getDepartamentos() {
        return this.departamentos;
    }
    
    public void setDepartamentos(Set departamentos) {
        this.departamentos = departamentos;
    }
    public Set getAduanas() {
        return this.aduanas;
    }
    
    public void setAduanas(Set aduanas) {
        this.aduanas = aduanas;
    }




}


