package aduana.modelo;
// Generated 11-20-2016 10:33:46 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Perfilexportador generated by hbm2java
 */
public class Perfilexportador  implements java.io.Serializable {


     private int idPerfilexpor;
     private String codigoPerfilexpor;
     private String domicilioPerfilexpor;
     private String idtributarioPerfilexpor;
     private Set usuarios = new HashSet(0);

    public Perfilexportador() {
    }

	
    public Perfilexportador(int idPerfilexpor, String codigoPerfilexpor, String domicilioPerfilexpor, String idtributarioPerfilexpor) {
        this.idPerfilexpor = idPerfilexpor;
        this.codigoPerfilexpor = codigoPerfilexpor;
        this.domicilioPerfilexpor = domicilioPerfilexpor;
        this.idtributarioPerfilexpor = idtributarioPerfilexpor;
    }
    public Perfilexportador(int idPerfilexpor, String codigoPerfilexpor, String domicilioPerfilexpor, String idtributarioPerfilexpor, Set usuarios) {
       this.idPerfilexpor = idPerfilexpor;
       this.codigoPerfilexpor = codigoPerfilexpor;
       this.domicilioPerfilexpor = domicilioPerfilexpor;
       this.idtributarioPerfilexpor = idtributarioPerfilexpor;
       this.usuarios = usuarios;
    }
   
    public int getIdPerfilexpor() {
        return this.idPerfilexpor;
    }
    
    public void setIdPerfilexpor(int idPerfilexpor) {
        this.idPerfilexpor = idPerfilexpor;
    }
    public String getCodigoPerfilexpor() {
        return this.codigoPerfilexpor;
    }
    
    public void setCodigoPerfilexpor(String codigoPerfilexpor) {
        this.codigoPerfilexpor = codigoPerfilexpor;
    }
    public String getDomicilioPerfilexpor() {
        return this.domicilioPerfilexpor;
    }
    
    public void setDomicilioPerfilexpor(String domicilioPerfilexpor) {
        this.domicilioPerfilexpor = domicilioPerfilexpor;
    }
    public String getIdtributarioPerfilexpor() {
        return this.idtributarioPerfilexpor;
    }
    
    public void setIdtributarioPerfilexpor(String idtributarioPerfilexpor) {
        this.idtributarioPerfilexpor = idtributarioPerfilexpor;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


