package aduana.modelo;
// Generated 11-30-2016 03:24:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Perfilexportador generated by hbm2java
 */
public class Perfilexportador  implements java.io.Serializable {


     private int idPe;
     private String codigoPe;
     private String domicilioPe;
     private String idtributarioPe;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Perfilexportador() {
    }

	
    public Perfilexportador(int idPe, String codigoPe, String domicilioPe, String idtributarioPe) {
        this.idPe = idPe;
        this.codigoPe = codigoPe;
        this.domicilioPe = domicilioPe;
        this.idtributarioPe = idtributarioPe;
    }
    public Perfilexportador(int idPe, String codigoPe, String domicilioPe, String idtributarioPe, Set<Usuario> usuarios) {
       this.idPe = idPe;
       this.codigoPe = codigoPe;
       this.domicilioPe = domicilioPe;
       this.idtributarioPe = idtributarioPe;
       this.usuarios = usuarios;
    }
   
    public int getIdPe() {
        return this.idPe;
    }
    
    public void setIdPe(int idPe) {
        this.idPe = idPe;
    }
    public String getCodigoPe() {
        return this.codigoPe;
    }
    
    public void setCodigoPe(String codigoPe) {
        this.codigoPe = codigoPe;
    }
    public String getDomicilioPe() {
        return this.domicilioPe;
    }
    
    public void setDomicilioPe(String domicilioPe) {
        this.domicilioPe = domicilioPe;
    }
    public String getIdtributarioPe() {
        return this.idtributarioPe;
    }
    
    public void setIdtributarioPe(String idtributarioPe) {
        this.idtributarioPe = idtributarioPe;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


