package aduana.modelo;
// Generated 11-20-2016 10:33:46 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private int idProd;
     private Arancel arancel;
     private Pais paisByPaiIdPais;
     private Pais paisByIdPais;
     private String nombreProd;
     private double pesoProd;
     private Set tipoproductos = new HashSet(0);
     private Set formularioarancelarios = new HashSet(0);

    public Producto() {
    }

	
    public Producto(int idProd, String nombreProd, double pesoProd) {
        this.idProd = idProd;
        this.nombreProd = nombreProd;
        this.pesoProd = pesoProd;
    }
    public Producto(int idProd, Arancel arancel, Pais paisByPaiIdPais, Pais paisByIdPais, String nombreProd, double pesoProd, Set tipoproductos, Set formularioarancelarios) {
       this.idProd = idProd;
       this.arancel = arancel;
       this.paisByPaiIdPais = paisByPaiIdPais;
       this.paisByIdPais = paisByIdPais;
       this.nombreProd = nombreProd;
       this.pesoProd = pesoProd;
       this.tipoproductos = tipoproductos;
       this.formularioarancelarios = formularioarancelarios;
    }
   
    public int getIdProd() {
        return this.idProd;
    }
    
    public void setIdProd(int idProd) {
        this.idProd = idProd;
    }
    public Arancel getArancel() {
        return this.arancel;
    }
    
    public void setArancel(Arancel arancel) {
        this.arancel = arancel;
    }
    public Pais getPaisByPaiIdPais() {
        return this.paisByPaiIdPais;
    }
    
    public void setPaisByPaiIdPais(Pais paisByPaiIdPais) {
        this.paisByPaiIdPais = paisByPaiIdPais;
    }
    public Pais getPaisByIdPais() {
        return this.paisByIdPais;
    }
    
    public void setPaisByIdPais(Pais paisByIdPais) {
        this.paisByIdPais = paisByIdPais;
    }
    public String getNombreProd() {
        return this.nombreProd;
    }
    
    public void setNombreProd(String nombreProd) {
        this.nombreProd = nombreProd;
    }
    public double getPesoProd() {
        return this.pesoProd;
    }
    
    public void setPesoProd(double pesoProd) {
        this.pesoProd = pesoProd;
    }
    public Set getTipoproductos() {
        return this.tipoproductos;
    }
    
    public void setTipoproductos(Set tipoproductos) {
        this.tipoproductos = tipoproductos;
    }
    public Set getFormularioarancelarios() {
        return this.formularioarancelarios;
    }
    
    public void setFormularioarancelarios(Set formularioarancelarios) {
        this.formularioarancelarios = formularioarancelarios;
    }




}


