package aduana.modelo;
// Generated 11-30-2016 03:24:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private int idProd;
     private Arancel arancel;
     private Pais paisByIdPais;
     private Pais paisByPaiIdPais;
     private Tipoproducto tipoproducto;
     private String nombreProd;
     private double pesoProd;
     private Set<Formularioarancelario> formularioarancelarios = new HashSet<Formularioarancelario>(0);

    public Producto() {
    }

	
    public Producto(int idProd, Arancel arancel, Pais paisByIdPais, Pais paisByPaiIdPais, Tipoproducto tipoproducto, String nombreProd, double pesoProd) {
        this.idProd = idProd;
        this.arancel = arancel;
        this.paisByIdPais = paisByIdPais;
        this.paisByPaiIdPais = paisByPaiIdPais;
        this.tipoproducto = tipoproducto;
        this.nombreProd = nombreProd;
        this.pesoProd = pesoProd;
    }
    public Producto(int idProd, Arancel arancel, Pais paisByIdPais, Pais paisByPaiIdPais, Tipoproducto tipoproducto, String nombreProd, double pesoProd, Set<Formularioarancelario> formularioarancelarios) {
       this.idProd = idProd;
       this.arancel = arancel;
       this.paisByIdPais = paisByIdPais;
       this.paisByPaiIdPais = paisByPaiIdPais;
       this.tipoproducto = tipoproducto;
       this.nombreProd = nombreProd;
       this.pesoProd = pesoProd;
       this.formularioarancelarios = formularioarancelarios;
    }
   
    public int getIdProd() {
        return this.idProd;
    }
    
    public void setIdProd(int idProd) {
        this.idProd = idProd;
    }
    public Arancel getArancel() {
        return this.arancel;
    }
    
    public void setArancel(Arancel arancel) {
        this.arancel = arancel;
    }
    public Pais getPaisByIdPais() {
        return this.paisByIdPais;
    }
    
    public void setPaisByIdPais(Pais paisByIdPais) {
        this.paisByIdPais = paisByIdPais;
    }
    public Pais getPaisByPaiIdPais() {
        return this.paisByPaiIdPais;
    }
    
    public void setPaisByPaiIdPais(Pais paisByPaiIdPais) {
        this.paisByPaiIdPais = paisByPaiIdPais;
    }
    public Tipoproducto getTipoproducto() {
        return this.tipoproducto;
    }
    
    public void setTipoproducto(Tipoproducto tipoproducto) {
        this.tipoproducto = tipoproducto;
    }
    public String getNombreProd() {
        return this.nombreProd;
    }
    
    public void setNombreProd(String nombreProd) {
        this.nombreProd = nombreProd;
    }
    public double getPesoProd() {
        return this.pesoProd;
    }
    
    public void setPesoProd(double pesoProd) {
        this.pesoProd = pesoProd;
    }
    public Set<Formularioarancelario> getFormularioarancelarios() {
        return this.formularioarancelarios;
    }
    
    public void setFormularioarancelarios(Set<Formularioarancelario> formularioarancelarios) {
        this.formularioarancelarios = formularioarancelarios;
    }




}


