package aduana.modelo;
<<<<<<< HEAD
// Generated 11-30-2016 03:24:13 PM by Hibernate Tools 4.3.1
=======
// Generated 11-20-2016 10:33:46 AM by Hibernate Tools 4.3.1
>>>>>>> ded8ed45bf60eccdd9124f32bde57f757b9c0fe3


import java.util.HashSet;
import java.util.Set;

/**
 * Tipousuario generated by hbm2java
 */
public class Tipousuario  implements java.io.Serializable {


<<<<<<< HEAD
     private int idTu;
     private String codigoTu;
     private String nombreTu;
     private String descripcionTu;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);
=======
     private int idTipousuario;
     private String codigoTipousuario;
     private String nombreTipousuario;
     private String descripcioTipousuario;
     private Set usuarios = new HashSet(0);
>>>>>>> ded8ed45bf60eccdd9124f32bde57f757b9c0fe3

    public Tipousuario() {
    }

	
<<<<<<< HEAD
    public Tipousuario(int idTu, String codigoTu, String nombreTu, String descripcionTu) {
        this.idTu = idTu;
        this.codigoTu = codigoTu;
        this.nombreTu = nombreTu;
        this.descripcionTu = descripcionTu;
    }
    public Tipousuario(int idTu, String codigoTu, String nombreTu, String descripcionTu, Set<Usuario> usuarios) {
       this.idTu = idTu;
       this.codigoTu = codigoTu;
       this.nombreTu = nombreTu;
       this.descripcionTu = descripcionTu;
       this.usuarios = usuarios;
    }
   
    public int getIdTu() {
        return this.idTu;
    }
    
    public void setIdTu(int idTu) {
        this.idTu = idTu;
    }
    public String getCodigoTu() {
        return this.codigoTu;
    }
    
    public void setCodigoTu(String codigoTu) {
        this.codigoTu = codigoTu;
    }
    public String getNombreTu() {
        return this.nombreTu;
    }
    
    public void setNombreTu(String nombreTu) {
        this.nombreTu = nombreTu;
    }
    public String getDescripcionTu() {
        return this.descripcionTu;
    }
    
    public void setDescripcionTu(String descripcionTu) {
        this.descripcionTu = descripcionTu;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
=======
    public Tipousuario(int idTipousuario, String codigoTipousuario, String nombreTipousuario, String descripcioTipousuario) {
        this.idTipousuario = idTipousuario;
        this.codigoTipousuario = codigoTipousuario;
        this.nombreTipousuario = nombreTipousuario;
        this.descripcioTipousuario = descripcioTipousuario;
    }
    public Tipousuario(int idTipousuario, String codigoTipousuario, String nombreTipousuario, String descripcioTipousuario, Set usuarios) {
       this.idTipousuario = idTipousuario;
       this.codigoTipousuario = codigoTipousuario;
       this.nombreTipousuario = nombreTipousuario;
       this.descripcioTipousuario = descripcioTipousuario;
       this.usuarios = usuarios;
    }
   
    public int getIdTipousuario() {
        return this.idTipousuario;
    }
    
    public void setIdTipousuario(int idTipousuario) {
        this.idTipousuario = idTipousuario;
    }
    public String getCodigoTipousuario() {
        return this.codigoTipousuario;
    }
    
    public void setCodigoTipousuario(String codigoTipousuario) {
        this.codigoTipousuario = codigoTipousuario;
    }
    public String getNombreTipousuario() {
        return this.nombreTipousuario;
    }
    
    public void setNombreTipousuario(String nombreTipousuario) {
        this.nombreTipousuario = nombreTipousuario;
    }
    public String getDescripcioTipousuario() {
        return this.descripcioTipousuario;
    }
    
    public void setDescripcioTipousuario(String descripcioTipousuario) {
        this.descripcioTipousuario = descripcioTipousuario;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
>>>>>>> ded8ed45bf60eccdd9124f32bde57f757b9c0fe3
        this.usuarios = usuarios;
    }




}


