package aduana.modelo;
// Generated 11-30-2016 03:24:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipoarancel generated by hbm2java
 */
public class Tipoarancel  implements java.io.Serializable {


     private int idTarancel;
     private String descripcionTarancel;
     private String clasificacionTarancel;
     private String codigoTarancel;
     private Set<Arancel> arancels = new HashSet<Arancel>(0);

    public Tipoarancel() {
    }

	
    public Tipoarancel(int idTarancel, String descripcionTarancel, String clasificacionTarancel, String codigoTarancel) {
        this.idTarancel = idTarancel;
        this.descripcionTarancel = descripcionTarancel;
        this.clasificacionTarancel = clasificacionTarancel;
        this.codigoTarancel = codigoTarancel;
    }
    public Tipoarancel(int idTarancel, String descripcionTarancel, String clasificacionTarancel, String codigoTarancel, Set<Arancel> arancels) {
       this.idTarancel = idTarancel;
       this.descripcionTarancel = descripcionTarancel;
       this.clasificacionTarancel = clasificacionTarancel;
       this.codigoTarancel = codigoTarancel;
       this.arancels = arancels;
    }
   
    public int getIdTarancel() {
        return this.idTarancel;
    }
    
    public void setIdTarancel(int idTarancel) {
        this.idTarancel = idTarancel;
    }
    public String getDescripcionTarancel() {
        return this.descripcionTarancel;
    }
    
    public void setDescripcionTarancel(String descripcionTarancel) {
        this.descripcionTarancel = descripcionTarancel;
    }
    public String getClasificacionTarancel() {
        return this.clasificacionTarancel;
    }
    
    public void setClasificacionTarancel(String clasificacionTarancel) {
        this.clasificacionTarancel = clasificacionTarancel;
    }
    public String getCodigoTarancel() {
        return this.codigoTarancel;
    }
    
    public void setCodigoTarancel(String codigoTarancel) {
        this.codigoTarancel = codigoTarancel;
    }
    public Set<Arancel> getArancels() {
        return this.arancels;
    }
    
    public void setArancels(Set<Arancel> arancels) {
        this.arancels = arancels;
    }




}


