package aduana.modelo;
// Generated 11-20-2016 10:33:46 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipopago generated by hbm2java
 */
public class Tipopago  implements java.io.Serializable {


     private int idTipopago;
     private String codigoTipopago;
     private String nombreTipopago;
     private String descripcionTipopago;
     private Set pagos = new HashSet(0);

    public Tipopago() {
    }

	
    public Tipopago(int idTipopago, String codigoTipopago, String nombreTipopago, String descripcionTipopago) {
        this.idTipopago = idTipopago;
        this.codigoTipopago = codigoTipopago;
        this.nombreTipopago = nombreTipopago;
        this.descripcionTipopago = descripcionTipopago;
    }
    public Tipopago(int idTipopago, String codigoTipopago, String nombreTipopago, String descripcionTipopago, Set pagos) {
       this.idTipopago = idTipopago;
       this.codigoTipopago = codigoTipopago;
       this.nombreTipopago = nombreTipopago;
       this.descripcionTipopago = descripcionTipopago;
       this.pagos = pagos;
    }
   
    public int getIdTipopago() {
        return this.idTipopago;
    }
    
    public void setIdTipopago(int idTipopago) {
        this.idTipopago = idTipopago;
    }
    public String getCodigoTipopago() {
        return this.codigoTipopago;
    }
    
    public void setCodigoTipopago(String codigoTipopago) {
        this.codigoTipopago = codigoTipopago;
    }
    public String getNombreTipopago() {
        return this.nombreTipopago;
    }
    
    public void setNombreTipopago(String nombreTipopago) {
        this.nombreTipopago = nombreTipopago;
    }
    public String getDescripcionTipopago() {
        return this.descripcionTipopago;
    }
    
    public void setDescripcionTipopago(String descripcionTipopago) {
        this.descripcionTipopago = descripcionTipopago;
    }
    public Set getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set pagos) {
        this.pagos = pagos;
    }




}


