package aduana.modelo;
// Generated 11-20-2016 10:33:46 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipoarancel generated by hbm2java
 */
public class Tipoarancel  implements java.io.Serializable {


     private int idTipoarancel;
     private String descripcionTipoarancel;
     private String clasificacionTipoarancel;
     private String codigoTipoarancel;
     private Set arancels = new HashSet(0);

    public Tipoarancel() {
    }

	
    public Tipoarancel(int idTipoarancel, String descripcionTipoarancel, String clasificacionTipoarancel, String codigoTipoarancel) {
        this.idTipoarancel = idTipoarancel;
        this.descripcionTipoarancel = descripcionTipoarancel;
        this.clasificacionTipoarancel = clasificacionTipoarancel;
        this.codigoTipoarancel = codigoTipoarancel;
    }
    public Tipoarancel(int idTipoarancel, String descripcionTipoarancel, String clasificacionTipoarancel, String codigoTipoarancel, Set arancels) {
       this.idTipoarancel = idTipoarancel;
       this.descripcionTipoarancel = descripcionTipoarancel;
       this.clasificacionTipoarancel = clasificacionTipoarancel;
       this.codigoTipoarancel = codigoTipoarancel;
       this.arancels = arancels;
    }
   
    public int getIdTipoarancel() {
        return this.idTipoarancel;
    }
    
    public void setIdTipoarancel(int idTipoarancel) {
        this.idTipoarancel = idTipoarancel;
    }
    public String getDescripcionTipoarancel() {
        return this.descripcionTipoarancel;
    }
    
    public void setDescripcionTipoarancel(String descripcionTipoarancel) {
        this.descripcionTipoarancel = descripcionTipoarancel;
    }
    public String getClasificacionTipoarancel() {
        return this.clasificacionTipoarancel;
    }
    
    public void setClasificacionTipoarancel(String clasificacionTipoarancel) {
        this.clasificacionTipoarancel = clasificacionTipoarancel;
    }
    public String getCodigoTipoarancel() {
        return this.codigoTipoarancel;
    }
    
    public void setCodigoTipoarancel(String codigoTipoarancel) {
        this.codigoTipoarancel = codigoTipoarancel;
    }
    public Set getArancels() {
        return this.arancels;
    }
    
    public void setArancels(Set arancels) {
        this.arancels = arancels;
    }




}


