package aduana.modelo;
// Generated 11-30-2016 03:24:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipoproducto generated by hbm2java
 */
public class Tipoproducto  implements java.io.Serializable {


     private int idTipopro;
     private String descripcionTipopro;
     private String clasificacionTipopro;
     private String codigoTipopro;
     private Set<Producto> productos = new HashSet<Producto>(0);

    public Tipoproducto() {
    }

	
    public Tipoproducto(int idTipopro, String descripcionTipopro, String clasificacionTipopro, String codigoTipopro) {
        this.idTipopro = idTipopro;
        this.descripcionTipopro = descripcionTipopro;
        this.clasificacionTipopro = clasificacionTipopro;
        this.codigoTipopro = codigoTipopro;
    }
    public Tipoproducto(int idTipopro, String descripcionTipopro, String clasificacionTipopro, String codigoTipopro, Set<Producto> productos) {
       this.idTipopro = idTipopro;
       this.descripcionTipopro = descripcionTipopro;
       this.clasificacionTipopro = clasificacionTipopro;
       this.codigoTipopro = codigoTipopro;
       this.productos = productos;
    }
   
    public int getIdTipopro() {
        return this.idTipopro;
    }
    
    public void setIdTipopro(int idTipopro) {
        this.idTipopro = idTipopro;
    }
    public String getDescripcionTipopro() {
        return this.descripcionTipopro;
    }
    
    public void setDescripcionTipopro(String descripcionTipopro) {
        this.descripcionTipopro = descripcionTipopro;
    }
    public String getClasificacionTipopro() {
        return this.clasificacionTipopro;
    }
    
    public void setClasificacionTipopro(String clasificacionTipopro) {
        this.clasificacionTipopro = clasificacionTipopro;
    }
    public String getCodigoTipopro() {
        return this.codigoTipopro;
    }
    
    public void setCodigoTipopro(String codigoTipopro) {
        this.codigoTipopro = codigoTipopro;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }




}


