package aduana.modelo;
// Generated 11-30-2016 03:24:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipousuario generated by hbm2java
 */
public class Tipousuario  implements java.io.Serializable {


     private int idTu;
     private String codigoTu;
     private String nombreTu;
     private String descripcionTu;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Tipousuario() {
    }

	
    public Tipousuario(int idTu, String codigoTu, String nombreTu, String descripcionTu) {
        this.idTu = idTu;
        this.codigoTu = codigoTu;
        this.nombreTu = nombreTu;
        this.descripcionTu = descripcionTu;
    }
    public Tipousuario(int idTu, String codigoTu, String nombreTu, String descripcionTu, Set<Usuario> usuarios) {
       this.idTu = idTu;
       this.codigoTu = codigoTu;
       this.nombreTu = nombreTu;
       this.descripcionTu = descripcionTu;
       this.usuarios = usuarios;
    }
   
    public int getIdTu() {
        return this.idTu;
    }
    
    public void setIdTu(int idTu) {
        this.idTu = idTu;
    }
    public String getCodigoTu() {
        return this.codigoTu;
    }
    
    public void setCodigoTu(String codigoTu) {
        this.codigoTu = codigoTu;
    }
    public String getNombreTu() {
        return this.nombreTu;
    }
    
    public void setNombreTu(String nombreTu) {
        this.nombreTu = nombreTu;
    }
    public String getDescripcionTu() {
        return this.descripcionTu;
    }
    
    public void setDescripcionTu(String descripcionTu) {
        this.descripcionTu = descripcionTu;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


