package aduana.modelo;
<<<<<<< HEAD
// Generated 11-30-2016 03:24:13 PM by Hibernate Tools 4.3.1
=======
// Generated 11-20-2016 10:33:46 AM by Hibernate Tools 4.3.1
>>>>>>> ded8ed45bf60eccdd9124f32bde57f757b9c0fe3


import java.util.HashSet;
import java.util.Set;

/**
 * Tipopago generated by hbm2java
 */
public class Tipopago  implements java.io.Serializable {


     private int idTipopago;
     private String codigoTipopago;
     private String nombreTipopago;
     private String descripcionTipopago;
<<<<<<< HEAD
     private Set<Pago> pagos = new HashSet<Pago>(0);
=======
     private Set pagos = new HashSet(0);
>>>>>>> ded8ed45bf60eccdd9124f32bde57f757b9c0fe3

    public Tipopago() {
    }

	
    public Tipopago(int idTipopago, String codigoTipopago, String nombreTipopago, String descripcionTipopago) {
        this.idTipopago = idTipopago;
        this.codigoTipopago = codigoTipopago;
        this.nombreTipopago = nombreTipopago;
        this.descripcionTipopago = descripcionTipopago;
    }
<<<<<<< HEAD
    public Tipopago(int idTipopago, String codigoTipopago, String nombreTipopago, String descripcionTipopago, Set<Pago> pagos) {
=======
    public Tipopago(int idTipopago, String codigoTipopago, String nombreTipopago, String descripcionTipopago, Set pagos) {
>>>>>>> ded8ed45bf60eccdd9124f32bde57f757b9c0fe3
       this.idTipopago = idTipopago;
       this.codigoTipopago = codigoTipopago;
       this.nombreTipopago = nombreTipopago;
       this.descripcionTipopago = descripcionTipopago;
       this.pagos = pagos;
    }
   
    public int getIdTipopago() {
        return this.idTipopago;
    }
    
    public void setIdTipopago(int idTipopago) {
        this.idTipopago = idTipopago;
    }
    public String getCodigoTipopago() {
        return this.codigoTipopago;
    }
    
    public void setCodigoTipopago(String codigoTipopago) {
        this.codigoTipopago = codigoTipopago;
    }
    public String getNombreTipopago() {
        return this.nombreTipopago;
    }
    
    public void setNombreTipopago(String nombreTipopago) {
        this.nombreTipopago = nombreTipopago;
    }
    public String getDescripcionTipopago() {
        return this.descripcionTipopago;
    }
    
    public void setDescripcionTipopago(String descripcionTipopago) {
        this.descripcionTipopago = descripcionTipopago;
    }
<<<<<<< HEAD
    public Set<Pago> getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set<Pago> pagos) {
=======
    public Set getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set pagos) {
>>>>>>> ded8ed45bf60eccdd9124f32bde57f757b9c0fe3
        this.pagos = pagos;
    }




}


