package aduana.modelo;
// Generated 11-20-2016 10:33:46 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Transporte generated by hbm2java
 */
public class Transporte  implements java.io.Serializable {


     private int idTransp;
     private Tipotransporte tipotransporte;
     private String nombreTransp;
     private String descripcionTransp;
     private Set formularioexportacions = new HashSet(0);

    public Transporte() {
    }

	
    public Transporte(int idTransp, String nombreTransp, String descripcionTransp) {
        this.idTransp = idTransp;
        this.nombreTransp = nombreTransp;
        this.descripcionTransp = descripcionTransp;
    }
    public Transporte(int idTransp, Tipotransporte tipotransporte, String nombreTransp, String descripcionTransp, Set formularioexportacions) {
       this.idTransp = idTransp;
       this.tipotransporte = tipotransporte;
       this.nombreTransp = nombreTransp;
       this.descripcionTransp = descripcionTransp;
       this.formularioexportacions = formularioexportacions;
    }
   
    public int getIdTransp() {
        return this.idTransp;
    }
    
    public void setIdTransp(int idTransp) {
        this.idTransp = idTransp;
    }
    public Tipotransporte getTipotransporte() {
        return this.tipotransporte;
    }
    
    public void setTipotransporte(Tipotransporte tipotransporte) {
        this.tipotransporte = tipotransporte;
    }
    public String getNombreTransp() {
        return this.nombreTransp;
    }
    
    public void setNombreTransp(String nombreTransp) {
        this.nombreTransp = nombreTransp;
    }
    public String getDescripcionTransp() {
        return this.descripcionTransp;
    }
    
    public void setDescripcionTransp(String descripcionTransp) {
        this.descripcionTransp = descripcionTransp;
    }
    public Set getFormularioexportacions() {
        return this.formularioexportacions;
    }
    
    public void setFormularioexportacions(Set formularioexportacions) {
        this.formularioexportacions = formularioexportacions;
    }




}


