package aduana.modelo;
// Generated 11-30-2016 03:24:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private Perfilexportador perfilexportador;
     private Tipousuario tipousuario;
     private String nombreUsuario;
     private String passwordUsuario;
     private Set<Formularioarancelario> formularioarancelarios = new HashSet<Formularioarancelario>(0);
     private Set<Otrosformularios> otrosformularioses = new HashSet<Otrosformularios>(0);
     private Set<Formularioexportacion> formularioexportacions = new HashSet<Formularioexportacion>(0);

    public Usuario() {
    }

	
    public Usuario(int idUsuario, Perfilexportador perfilexportador, Tipousuario tipousuario, String nombreUsuario, String passwordUsuario) {
        this.idUsuario = idUsuario;
        this.perfilexportador = perfilexportador;
        this.tipousuario = tipousuario;
        this.nombreUsuario = nombreUsuario;
        this.passwordUsuario = passwordUsuario;
    }
    public Usuario(int idUsuario, Perfilexportador perfilexportador, Tipousuario tipousuario, String nombreUsuario, String passwordUsuario, Set<Formularioarancelario> formularioarancelarios, Set<Otrosformularios> otrosformularioses, Set<Formularioexportacion> formularioexportacions) {
       this.idUsuario = idUsuario;
       this.perfilexportador = perfilexportador;
       this.tipousuario = tipousuario;
       this.nombreUsuario = nombreUsuario;
       this.passwordUsuario = passwordUsuario;
       this.formularioarancelarios = formularioarancelarios;
       this.otrosformularioses = otrosformularioses;
       this.formularioexportacions = formularioexportacions;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Perfilexportador getPerfilexportador() {
        return this.perfilexportador;
    }
    
    public void setPerfilexportador(Perfilexportador perfilexportador) {
        this.perfilexportador = perfilexportador;
    }
    public Tipousuario getTipousuario() {
        return this.tipousuario;
    }
    
    public void setTipousuario(Tipousuario tipousuario) {
        this.tipousuario = tipousuario;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getPasswordUsuario() {
        return this.passwordUsuario;
    }
    
    public void setPasswordUsuario(String passwordUsuario) {
        this.passwordUsuario = passwordUsuario;
    }
    public Set<Formularioarancelario> getFormularioarancelarios() {
        return this.formularioarancelarios;
    }
    
    public void setFormularioarancelarios(Set<Formularioarancelario> formularioarancelarios) {
        this.formularioarancelarios = formularioarancelarios;
    }
    public Set<Otrosformularios> getOtrosformularioses() {
        return this.otrosformularioses;
    }
    
    public void setOtrosformularioses(Set<Otrosformularios> otrosformularioses) {
        this.otrosformularioses = otrosformularioses;
    }
    public Set<Formularioexportacion> getFormularioexportacions() {
        return this.formularioexportacions;
    }
    
    public void setFormularioexportacions(Set<Formularioexportacion> formularioexportacions) {
        this.formularioexportacions = formularioexportacions;
    }




}


