package aduana.modelo;
// Generated 11-20-2016 10:33:46 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private Perfilexportador perfilexportador;
     private Tipousuario tipousuario;
     private String nombreUsuario;
     private String passwordUsuario;
     private Set formularioarancelarios = new HashSet(0);
     private Set otrosformularioses = new HashSet(0);
     private Set formularioexportacions = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int idUsuario, String nombreUsuario, String passwordUsuario) {
        this.idUsuario = idUsuario;
        this.nombreUsuario = nombreUsuario;
        this.passwordUsuario = passwordUsuario;
    }
    public Usuario(int idUsuario, Perfilexportador perfilexportador, Tipousuario tipousuario, String nombreUsuario, String passwordUsuario, Set formularioarancelarios, Set otrosformularioses, Set formularioexportacions) {
       this.idUsuario = idUsuario;
       this.perfilexportador = perfilexportador;
       this.tipousuario = tipousuario;
       this.nombreUsuario = nombreUsuario;
       this.passwordUsuario = passwordUsuario;
       this.formularioarancelarios = formularioarancelarios;
       this.otrosformularioses = otrosformularioses;
       this.formularioexportacions = formularioexportacions;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Perfilexportador getPerfilexportador() {
        return this.perfilexportador;
    }
    
    public void setPerfilexportador(Perfilexportador perfilexportador) {
        this.perfilexportador = perfilexportador;
    }
    public Tipousuario getTipousuario() {
        return this.tipousuario;
    }
    
    public void setTipousuario(Tipousuario tipousuario) {
        this.tipousuario = tipousuario;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getPasswordUsuario() {
        return this.passwordUsuario;
    }
    
    public void setPasswordUsuario(String passwordUsuario) {
        this.passwordUsuario = passwordUsuario;
    }
    public Set getFormularioarancelarios() {
        return this.formularioarancelarios;
    }
    
    public void setFormularioarancelarios(Set formularioarancelarios) {
        this.formularioarancelarios = formularioarancelarios;
    }
    public Set getOtrosformularioses() {
        return this.otrosformularioses;
    }
    
    public void setOtrosformularioses(Set otrosformularioses) {
        this.otrosformularioses = otrosformularioses;
    }
    public Set getFormularioexportacions() {
        return this.formularioexportacions;
    }
    
    public void setFormularioexportacions(Set formularioexportacions) {
        this.formularioexportacions = formularioexportacions;
    }




}


